# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.19.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
Z=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:

Z.size*Z.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)      

In [18]:
x=np.array([1,2,0,0,4,0])
x_indices_boolean=[x!=0]
np.arange(len(x))[x_indices_boolean]



C:\Users\jeehy\anaconda3\envs\test\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  This is separate from the ipykernel package so we can avoid doing imports until


array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [66]:
#indentity matrix함수: np.eye

In [69]:
matrix1=np.zeros((3,3))
for i in range(3):
    matrix1[i,i]=1
print(matrix1)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
#random value 생성: 1. np.random.randint(개수, 범위)
#                   2. np.random.rand(개수): 0~1사이 랜덤 생성
#                   3. np.random.randn(개수): 표준정규분포 생성
#                   4. np.random.uniform(low,high,num)     

In [29]:

matrix2=np.random.randint(low=0,high=10,size=27).reshape(3,3,3)
print("matrix2:\n",matrix2)


matrix2:
 [[[1 5 5]
  [1 6 4]
  [2 6 4]]

 [[3 3 1]
  [6 0 0]
  [6 8 8]]

 [[0 6 0]
  [0 3 8]
  [8 0 4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
# 넘파이 최대 최소 찾기 함수:np.max, np.min

In [59]:
matrix3=np.random.randint(low=0,high=101,size=100).reshape(10,10)
print("matrix3:",matrix3)
print(matrix3.max(),matrix3.min())

matrix3: [[ 54  69  98  49  66  39   1  90  50  97]
 [ 13  41  55   5  75   0  86  13   7  33]
 [ 68  72  20  21  47   1  26  17   2  11]
 [ 51  94  12  42  61   2  32  70  59  19]
 [ 57  71  10  36  59  56  45  12   6  54]
 [ 78  21  62  59  39  30  23  58  53  40]
 [ 65  90 100  41  90  47  57  35 100  50]
 [ 46  62  80  45   1  58  44   6  25   0]
 [  8  26  42  99  12  67  89  70  58  40]
 [ 12  32  83  66   5  97  40   7  84  43]]
100 0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
x=np.random.rand(30)*10
np.mean(x)

4.919730851430456

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [103]:
x=np.ones(9).reshape(3,3)
x[1,1]=0
print(x)


[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [104]:
#행렬에 열추가: np.c_, 행추가:np.r_

In [108]:
def add(matrix):
    row=matrix.shape[0]
    col=matrix.shape[1]
    matrix=np.insert(matrix,(0,col),0,axis=1)
    matrix=np.insert(matrix,(0,row),0,axis=0)
    return matrix


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [110]:
0 * np.nan

nan

In [111]:
0 * np.nan
print(np.nan == np.nan)
print(np.inf > np.nan)
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False
False


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [114]:
x=np.zeros(25).reshape(5,5)
for i in range(4):
    x[i+1,i]=i+1
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [116]:
x=np.zeros(64).reshape(8,8)
for i in range(8):
    if(i%2==0):
        k=(0,2,4,6)
        x[i,k]=1
    else:
        k=(1,3,5,7)
        x[i,k]=1
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [136]:
def elementindex(a,b,c,k):
    z=k//(a*b)
    k=k%(a*b)

    y=k//a
    k=k%a
    
    x=k-1
    
    return [x,y,z]

matrix=np.arange(6*7*8).reshape(6,7,8)
elementindex(6,7,8,100)
    


[3, 2, 2]

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [137]:
x=np.eye(2)
np.tile(x,(2,2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [139]:
matrix=np.random.randn(25).reshape(5,5)
matrix

array([[-0.46966724,  0.27285519, -1.2781858 ,  0.03115095, -0.82921116],
       [-0.2358673 ,  0.9697578 ,  1.98748409,  0.48608284, -2.2418504 ],
       [ 0.19845167,  1.22510118,  1.40918959, -0.06004615, -1.56213121],
       [ 0.66524686, -0.81436822, -1.03901685, -0.78628501, -0.94874075],
       [-0.31042717,  0.29907462, -0.37036745, -0.16259127,  0.1104957 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 뭔솔?

In [35]:
x = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(x)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\jeehy\anaconda3\envs\test\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [141]:
x=np.random.rand(5,3)*10
y=np.random.rand(3,2)*10
print(np.dot(x,y))

[[139.20984467 154.30793076]
 [ 25.52988779  29.66972228]
 [106.52924491 119.19683109]
 [ 71.42269635  69.81076589]
 [ 53.75166381  83.59489947]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 

In [164]:
def negation(array):
    indices=[3<i and i<8 for i in array]
    array[indices]=0
    return array

matrix=np.random.rand(10)*10
print(negation(matrix))


[0.         0.         0.         0.         1.06482122 0.
 0.46697897 0.         1.93203843 0.        ]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [168]:
print(list(range(5)))
      

[0, 1, 2, 3, 4]


In [165]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z  
1j*Z
Z/1/1
Z<Z>Z
```

In [171]:
z=np.random.rand(5)*10

In [172]:
z**z

array([1.52157095e+03, 5.38958428e+06, 4.44741262e+03, 1.03549426e+00,
       2.67926936e+00])

In [173]:
2<<z>>2

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [174]:
z<-z

array([False, False, False, False, False])

In [175]:
1j*z

array([0.+4.72116032j, 0.+7.62839991j, 0.+5.13454772j, 0.+1.03429731j,
       0.+1.75398301j])

In [176]:
z/1/1

array([4.72116032, 7.62839991, 5.13454772, 1.03429731, 1.75398301])

In [177]:
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [179]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\jeehy\anaconda3\envs\test\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\jeehy\anaconda3\envs\test\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# 넘파이 반올림
# np.around(data) : 소수점 자리 수를 반올림해서 정수로 만들어줌
# np.round(data, decimals) :  원하는 소수점 자리수에서 반올림
# np.ceil(data) : 소수점 자리 수를 올림해서 정수로 만들어줌
# np.floor(data) : 소수점 자리 수를 버림해서 정수로 만들어줌

In [13]:
x = np.random.uniform(-10,+10,10)
print(x)
print(np.round(x,0))

[-5.79817435  7.9217728   6.3194824   4.08179943  4.41467213 -4.56218812
  6.83469017 -4.33387326  0.08135668 -8.96956969]
[-6.  8.  6.  4.  4. -5.  7. -4.  0. -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [18]:
x=np.random.randint(0,10,10)
print(x)
y=np.random.randint(0,10,10)
print(y)
print(np.intersect1d(x,y))

[2 1 9 1 6 7 4 9 6 4]
[9 1 6 5 9 6 6 0 2 1]
[1 2 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [19]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [21]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


In [20]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
import datetime as dt
today=dt.date.today()
yesterday=today-dt.timedelta(1)
tomorrow=today+dt.timedelta(1)
print('yesterday:',yesterday)
print('today:',today)
print('tomorrow:',tomorrow)

yesterday: 2021-03-18
today: 2021-03-19
tomorrow: 2021-03-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)