# 공룡책 chapter2: 사이킷런으로 시작하는 머신러닝

## 1.사이킷런 소개와 특징

In [3]:
import sklearn
print(sklearn.__version__)

0.23.2


## 2.첫번째 머신러닝 만들어보기-붓꽃 품종 예측하기

sklearn.datasets: 데이터 세트를 생성하는 모듈의 모임. <br/> sklearn.tree: 트리기반 ML알고리즘을 구현한 클래스의 모임.<br/>
sklearn.model_selection: 학습데이터와 검증 데이터, 예측데이터로 데이터를 분리하거나 최적의 하이퍼 파라미터로 평가하기 위한 다양한 모듈의 모임

In [7]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [8]:
import pandas as pd
iris=load_iris()

In [11]:
iris_data=iris.data
iris_label=iris.target

In [12]:
print('iris target값:',iris_label)
print('iris target명:',iris.target_names)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


In [13]:
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [14]:
# 학습용 데이터와 테스트용 데이터 분리
X_train,X_test,y_train,y_test=train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

In [15]:
# DecisionTreeClassifier 객체 생성
dt_clf=DecisionTreeClassifier(random_state=11)
#학습 수행
dt_clf.fit(X_train,y_train)
#학습이 완료된 dt_clf 객체에서 테스트 데이터 세트로 예측 수행
pred=dt_clf.predict(X_test)

### 예측성능평가
여러가지가 있으나 여기서는 **정확도**로 측정. <br/>예측결과가 실제 레이블 값과 얼마나 정확하게 맞는지를 평가하는
지표.

In [17]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.933333


### 정리
1. 데이터 세트 분리 <br/>
2. 모델 학습 <br/>
3. 예측 수행 <br/>
4. 평가

## 3. 사이킷런의 기반 프레임워크 익히기

지도학습의 주요 두축인 분류와 회귀의 다양한 알고리즘을 구현한 모든 사이킷런 클래스는 fit()과 predict()만을
이용해 간단하게 학습과 예측결과를 반환. <br/>
분류(classifier)와 회귀(regressor)를 합쳐서 estimator클래스라고 부름. <br/>
지도학습의 모든 알고리즘을 구현한 클래스를 통칭해서 estimator라고 부름. <br/>
당연히 estimator 클래스는 fit()과 predict()를 내부에서 구현.

비지도학습에는 차원 축소, 클러스터링, 피처추출등의 클래스가 있음.
이들은 fit(), transform()메서드를 적용.<br/>
동시에 수행하는 fit_transform() 메서드도 있음<br/>
다만 비지도학습의 fit()은 지도학습에서의 학습과 같은 개념이 아니라 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전구조를 맞추는 작업을 의미.

### 내장된 데이터세트의 형태
딕셔너리 형태로 구성됨 <br/>
data(ndarray),target(ndarray), target_name(ndarray/list),feature_names(ndarray/list),DESCR(str)로 구성됨 <br/>

In [21]:
from sklearn.datasets import load_iris
iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


 bunch 클래스는 파이썬 딕셔너리 자료형과 유사

In [22]:
keys=iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


##  model selection모듈 소개

### 학습/테스트 데이터 세트 분리-train_test_split()

In [24]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data,train_label)

pred=dt_clf.predict(train_data)
print('예측 정확도:',accuracy_score(train_label,pred))

예측 정확도: 1.0


예측 정확도가 100%인 이유는 이미 학습한 학습 데이터 세트를 기반으로 예측했기 때문.
train_test_split필요

In [32]:
from sklearn.model_selection import train_test_split
dt_clf=DecisionTreeClassifier()
X_train,X_test,y_train,y_test=train_test_split(train_data,train_label,test_size=0.3,random_state=121)

In [33]:
dt_clf.fit(X_train,y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도:',accuracy_score(y_test,pred))

예측 정확도: 0.9555555555555556


### 교차검증

교차검증이 필요한 이유: 고정된 학습 데이터와 테스트 데이터로 평가를 하다 보면 테스트 데이터에만 과적합되는
학습 모델이 만들어져 다른 테스트용 데이터가 들어올 경우에는 성능이 저하됨.<br/>
따라서 **여러세트로 구성된 학습 데이터 세트와 검증 데이터 세트에서 학습과 평과를 수행해야함.**<br/>
=> 학습, 검증, 테스트 데이터 구분

#### k폴드 교차검증: k개의 데이터 폴드 세트를 만들어서 k번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행

In [39]:
from sklearn.model_selection import KFold

features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [40]:
#k폴드 구현 생략

#### stratified k 폴드: k폴드가 레이블 데이터 집합이 원본 데이터 집합의 레이블 분포를 학습 및 테스트 세트에 제대로 분배하지 못하는 경우의 문제를 해결. 

In [41]:
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [45]:
# 이슈가 발생하는 현상
kfold=KFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(iris_df):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차검증: {0}'.format(n_iter))
    print('학습 레이블 분포:\n',label_train.value_counts())
    print('검증 레이블 분포:\n',label_test.value_counts())

## 교차검증: 1
학습 레이블 분포:
 2    50
1    50
Name: label, dtype: int64
검증 레이블 분포:
 0    50
Name: label, dtype: int64
## 교차검증: 2
학습 레이블 분포:
 2    50
0    50
Name: label, dtype: int64
검증 레이블 분포:
 1    50
Name: label, dtype: int64
## 교차검증: 3
학습 레이블 분포:
 1    50
0    50
Name: label, dtype: int64
검증 레이블 분포:
 2    50
Name: label, dtype: int64


In [58]:
#stratified kfold 
from sklearn.model_selection import StratifiedKFold
n_iter=0
skf=StratifiedKFold(n_splits=3)
for train_index,test_index in skf.split(iris.data,iris.target):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n',label_train.value_counts())
    print('검증 레이블 데이터 분포:\n',label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
1    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
0    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
2    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
0    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
2    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
1    17
0    16
Name: label, dtype: int64


In [63]:
type(features)

numpy.ndarray

In [71]:
#stratified kfold 
import numpy as np
from sklearn.model_selection import StratifiedKFold
n_iter=0
cv_accuracy=[]
skf=StratifiedKFold(n_splits=3)
for train_index,test_index in skf.split(iris.data,iris.target):
    n_iter+=1
    dt_clf=DecisionTreeClassifier()
    X_train,X_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    dt_clf.fit(X_train,y_train)
    pred=dt_clf.predict(X_test)
    accuracy=np.round(accuracy_score(y_test,pred),4)
    print(accuracy)
    cv_accuracy.append(accuracy)
print(np.round(cv_accuracy,4))
print(np.mean(cv_accuracy))
    

0.98
0.92
0.98
[0.98 0.92 0.98]
0.96


In [72]:
#회귀(regressor)에서는 stratified kfold가 지원되지 않음. 회귀의 결정값은 연속형이기 때문에. 


#### cross_val_score() 한꺼번에 수행! 결과로 검증 정확도 리스트형태로 출력

In [73]:
from sklearn.model_selection import cross_val_score,cross_validate

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)
data=iris_data.data
label=iris_data.target

scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:',np.round(np.mean(scores)),4)

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 1.0 4


### GridSearchCV-교차검증과 최적 하이퍼 파라미터 튜닝을 한 번에

In [74]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=121)

dtree=DecisionTreeClassifier()

parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

import pandas as pd

grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)
grid_dtree.fit(X_train,y_train)
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [75]:
estimator=grid_dtree.best_estimator_

pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도:[0:4f].format(accuracy_score(y_test,pred))')

테스트 데이터 세트 정확도:[0:4f].format(accuracy_score(y_test,pred))


## 5. 데이터 전처리

### 데이터 인코딩

In [76]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [77]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [78]:
print('디코딩 원본값:',encoder.inverse_transform([4,5,3,2]))

디코딩 원본값: ['전자레인지' '컴퓨터' '선풍기' '믹서']


In [79]:
## 레이블 인코딩은 숫자의 중요도가 존재하는 회귀에는 사용하면 안됨.

In [82]:
## 원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

labels=labels.reshape(-1,1)

oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print('원핫 인코딩 데이터')
print(oh_labels.toarray())
print('원핫 인코딩 데이터 차원')
print(oh_labels.shape)

원핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원핫 인코딩 데이터 차원
(8, 6)


In [85]:
## 한번에 수행
df=pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

#### 피처 스케일링(표준화,정규화)
표준화-StandardScaler
정규화-MInMaxScaler

In [2]:
# StandardScaler
from sklearn.datasets import load_iris
import pandas as pd

iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)

print('feature 들의 평균값')
print(iris_df.mean())
print('\nfeature  들의 분산값')
print(iris_df.var())

feature 들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature  들의 분산값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [3]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)
iris_df_scaled=pd.DataFrame(iris_scaled,columns=iris.feature_names)
print('feature들의 평균값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산값')
print(iris_df_scaled.var())

feature들의 평균값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [4]:
# MinMaxScaler 데이터의 분포가 가우시안 분포가 아닐 경우에 min,max scale을 적용.
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

iris_df_scaled=pd.DataFrame(iris_scaled,columns=iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('feature들의 최대값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [5]:
iris_df_scaled.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.222222          0.625000           0.067797          0.041667
1           0.166667          0.416667           0.067797          0.041667
2           0.111111          0.500000           0.050847          0.041667
3           0.083333          0.458333           0.084746          0.041667
4           0.194444          0.666667           0.067797          0.041667

#### 학습데이터와 테스트데이터의 스케일링 변환 시 유의점
학습데이터로 fit된 scaler로 테스트데이터를 transform 시켜야함.
테스트 데이터로 scaler를 다시 fit 시키면 안됨.


In [9]:
import numpy as np

train_array=np.arange(0,11).reshape(-1,1)
test_array=np.arange(0,6).reshape(-1,1)

scaler=MinMaxScaler()
scaler.fit(train_array)

train_scaled=scaler.transform(train_array)
print('원본 train_array 데이터:',np.round(train_array.reshape(-1),2))
print('Scaled 된 train_array 데이터:',np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled 된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [10]:
test_scaled=scaler.transform(test_array)
print('원본 test_array 데이터:',np.round(test_array.reshape(-1),2))
print('Scaled 된 test_array 데이터:',np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
Scaled 된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]
